ShareMyThings/Controllers/UseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

using ShareMyThings.Controllers.ViewModelData;
using ShareMyThings.Models;
using ShareMyThings.Models.Util;
using ShareMyThings.ViewModel.Use;
using ShareMyThings.Models.Use;

namespace ShareMyThings.Controllers
{
    public class UseController : Controller
    {
        // GET: Use
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Calculate and format text and due fields to OK View.
        /// </summary>
        /// <param name="time"></param>
        /// <param name="due"></param>
        /// <param name="current"></param>
        /// <param name="now"></param>
        private static void CalcOkRow(out string time, out string due, DateTime current, DateTime now)
        {
            time = string.Format(current.Date != now.Date ? "{0:yyyy-MM-dd HH:mm}" : "{0:HH:mm}", current);

            var isDue = now > current;
            if (isDue)
            {
                due = "passed";
            }
            else
            {
                var difference = current.Subtract(now);

                due = difference.TotalHours > 24.0d
                    ? string.Format("{0}:{1:mm}", (int)difference.TotalHours, current)
                    : string.Format(@"{0:hh\:mm}", difference)
                ;
            }
        }

        // ReSharper disable once InconsistentNaming
        public ActionResult OK(string id)
        {
            // Use Case
            // I: User selects OK on th Start page
            // R: A welcome message is shown holding user name and item name from reservation.
            // R: The end time and the end time with slack is shown.
            // R: Next reservation start time with slack and start time is shwon if there is an reservation at the same date.
            //
            // I: The user can refresh the page to see the next reservation by pressing Refresh

            var viewModel = new OkViewModel();

            var useLiveData = true;
            Ok modelData;

            { // DemoData
                var template = new Ok
                {
                    ItemId = 1,
                    UserName = "UserName",
                    ItemName = "ItemName",
                    ReservationEnd = DateTime.Now,
                    ReservationSlackEnd = DateTime.Now,
                    ShowNextReservation = true,
                    NextReservationSlackStart = DateTime.Now,
                    NextReservationStart = DateTime.Now,
                    NextUserName = "NextUserName",
                    NextUserPhone = "NextUserPhone",
                    Now = DateTime.Now,
                };

                string demoValue;

                if (new DemoUtil<Ok>().LoadDemo(out modelData, out demoValue, Request, id, template))
                {
                    viewModel.DemoValue = demoValue;
                    useLiveData = false;
                }
            }

            if (useLiveData)
            {
                // TODO get data from Model.
                modelData = new Ok
                {
                    ItemId = 1,
                    UserName = "UserName",
                    ItemName = "ItemName",
                    ReservationEnd = DateTime.Now,
                    ReservationSlackEnd = DateTime.Now,
                    ShowNextReservation = true,
                    NextReservationSlackStart = DateTime.Now,
                    NextReservationStart = DateTime.Now,
                    NextUserName = "NextUserName",
                    NextUserPhone = "NextUserPhone",
                    Now = DateTime.Now,
                };
            }


            viewModel.Headline = modelData.ItemName;

            var now = modelData.Now;
            viewModel.Now = useLiveData ? "" : String.Format("{0:yyyy-MM-dd HH:mm}", now);

            string due;
            string time;

            {
                CalcOkRow(out time, out due, modelData.ReservationEnd, now);
                viewModel.ReservationEnd = new OkViewModelRow { Alert = "", Due = due, Time = time };
            }

            {
                CalcOkRow(out time, out due, modelData.ReservationSlackEnd, now);
                viewModel.ReservationSlackEnd = new OkViewModelRow { Alert = "", Due = due, Time = time };
            }

            {
                CalcOkRow(out time, out due, modelData.NextReservationSlackStart, now);
                viewModel.NextReservationSlackStart = new OkViewModelRow { Alert = "", Due = due, Time = time };
            }

            {
                CalcOkRow(out time, out due, modelData.NextReservationStart, now);
                viewModel.NextReservationStart = new OkViewModelRow { Alert = "", Due = due, Time = time };
            }

            viewModel.ShowNextReservation = modelData.ShowNextReservation;

            viewModel.HasOverlap = modelData.NextReservationSlackStart < modelData.ReservationSlackEnd
                ||
                modelData.NextReservationSlackStart < modelData.ReservationEnd
            ;
            viewModel.NextUserName = modelData.NextUserName;
            long t1;
            viewModel.NextUserPhone = new PhoneNumber
            {
                CountryCode = "+45"
                ,
                AreaCode = ""
                ,
                SubscriberNumber = "2117 4505"
                ,
                EnabledServiceList = new List<PhoneNumberServcieType> { PhoneNumberServcieType.Call }
            };




            viewModel.FormatProvider = Thread.CurrentThread.CurrentCulture;

            //var t2 = viewModel.NextUserPhone.ToString();
            //var t3 = viewModel.NextUserPhone.ToString("p", null);
            //var t4 = viewModel.NextUserPhone.ToString("P", null);
            //var t5 = viewModel.NextUserPhone.ToString("t", null);
            //var t6 = viewModel.NextUserPhone.ToString("s", null);


            return View(viewModel);
        }


        public ActionResult SelectItem()
        {
            var viewModel = new SelectItemViewModel
            {
                Headline = "Select an action on an item",
            };

            var useLiveData = true;
            Select modelData;

            { // DemoData
                var template = new Select
                {
                    ItemList = new List<SelectRow>
                    {
                        new SelectRow {Key=1,Display =  "ItemName" }
                    }
                };

                string demoValue;

                if (new DemoUtil<Select>().LoadDemo(out modelData, out demoValue, Request, null, template))
                {
                    viewModel.DemoValue = demoValue;
                    useLiveData = false;
                }
            }

            if (useLiveData)
            {
                // TODO get data from Model.
                modelData = new Select { ItemList = new List<SelectRow>() };
            }

            var itemList = new List<ItemRow>();
            foreach (var row in modelData.ItemList)
            {
                itemList.Add(new ItemRow { Key = row.Key, Display = row.Display, Url = string.Format("OK/{0}", row.Key) });
            }

            viewModel.ItemList = itemList;

            return View(viewModel);
        }


        public ActionResult ChangeStartValue(string id)
        {
            // Use Case
            // I: User selects Change from the Start page.
            // R: this page is shwon with the last stop value.
            // I: User enters new value and press Save
            // R: The Start page is shown
            //
            // Exceptions-
            // E1 the value the user entered is out of range or not nummeric.
            // - a value can not differ the last value by more than 9999 and must be greater than 0.
            // rules may be refined
            // R: An error message is shown
            // 
            // I: Second press Save on the same value 
            // R: The value is accepted the value and the Start page is shown


            var viewModel = new ChangeStartValueViewModel();

            var useLiveData = true;
            ChangeStartValue modelData;

            { // DemoData
                var template = new ChangeStartValue
                {
                    Id = 1,
                    Name = "Item name",
                    Value = 123456m,
                    UnitsName = "unit name",
                    ValueLabel = "odometer",
                };

                string demoValue;

                if (new DemoUtil<ChangeStartValue>().LoadDemo(out modelData, out demoValue, Request, id, template))
                {
                    viewModel.DemoValue = demoValue;
                    useLiveData = false;
                }
            }

            if (useLiveData)
            {
                // TODO get data from Model.
                modelData = new ChangeStartValue
                {
                    Id = 1,
                    Name = "Item name",
                    Value = 123456m,
                    UnitsName = "unit name",
                    ValueLabel = "odometer",
                };
            }


            viewModel.Headline = string.Format("Please enter new {0} value for {1}"
                , modelData.ValueLabel
                , modelData.Name
                );
            viewModel.ItemValueCurrent = modelData.Value;
            viewModel.ItemValueUnitName = modelData.UnitsName;
            viewModel.ItemValueNew = modelData.Value;
            viewModel.Id = modelData.Id.ToString();
            viewModel.ItemName = modelData.Name;

            return View(viewModel);

        }

        /// <summary>
        /// Start a trip.
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

ShareMyThings/Views/Shared/NextUser.cshtml
@Model string

@{
    <span>@Model.ToString("Next user {0} xxx")</span>
}

ShareMyThings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    
    <link href="~/Content/Buttons.css" rel="stylesheet" />
    <link href="~/Content/Eksperimental.css" rel="stylesheet" />
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/Makeup.css" rel="stylesheet" />
    
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Share my things", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @*@Html.ActionLink("Start", "Start", "Use", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Stop", "Stop", "Use", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Change", "Change", "Use", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @*                   "Text" - "Method" - "Controller", new { area = "Area" }, null )     *@
                    @*<li>@Html.ActionLink("Start", "Index", "Start", new { area = "Use" }, null)</li>
                        <li>@Html.ActionLink("Stop", "Index", "Stop", new { area = "Use" }, null)</li>
                        <li>@Html.ActionLink("Change", "Index", "Change", new { area = "Use" }, null)</li>*@
                    <li>@Html.ActionLink("Select", "SelectItem", "Use")</li>
                    <li>@Html.ActionLink("Stop", "Stop", "Use")</li>
                    <li>@Html.ActionLink("Change", "Change", "Use")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Share My Things</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>